# Lua is not officially supported, but an erlang environment will do.
language: erlang

env:
  global:
    - PACKAGE=zile
    - ROCKSPEC=zile-git-1.rockspec
    - LUAROCKS_CONFIG=build-aux/luarocks-config.lua
    - LUAROCKS_BASE=luarocks-2.1.1
    - LUAROCKS="$LUA $HOME/bin/luarocks"
  matrix:
    - LUA=lua5.2             LUA_INCDIR=/usr/include/lua5.2     LUA_SUFFIX=5.2

# Tool setup.
install:
  # Put back the links for libyaml, which went missing on recent Travis VMs
  - test -f /usr/lib/libyaml.so ||
    sudo find /usr/lib -name 'libyaml*' -exec ln -s {} /usr/lib \;

  - sudo apt-get install help2man
  - sudo apt-get install lua5.2
  - sudo apt-get install liblua5.2-dev
  - sudo apt-get install libonig-dev

  # Install a luarocks beta locally for everything else.
  - git clone --depth=1 https://github.com/keplerproject/luarocks.git
  # LuaRocks configure --with-lua argument is just a prefix!
  - ( cd luarocks;
      ./configure
      --prefix=$HOME --with-lua=/usr --lua-version=$LUA_SUFFIX
      --lua-suffix=$LUA_SUFFIX --with-lua-include=$LUA_INCDIR;
      make build;
      make install; )

# Configure and build.
script:
  # Initial bootstrap to build luarocks-config.lua, before we've
  # installed our rocks.
  - ./bootstrap --skip-rock-checks
  - ./configure LUA="$LUA"
  - make $LUAROCKS_CONFIG
    LUA="$LUA" LUA_INCDIR="$LUA_INCDIR" V=1
    || cat $LUAROCKS_CONFIG config.log

  # Set Lua and Shell paths up for local luarocks tree.
  # this package depends on will be installed.
  - eval `$LUAROCKS path`
  - export PATH=`pwd`/luarocks/bin:$PATH

  # Install extra rocks into $LUAROCKS_CONFIG rocks tree.
  - $LUAROCKS install lyaml; $LUAROCKS install specl; $LUAROCKS install ldoc

  # Make git rockspec for zile
  - make rockspecs LUAROCKS="$LUAROCKS" V=1
    || { $LUAROCKS path; cat $ROCKSPEC; }

  # The git rockspec will rerun bootstrap, and check any rock versions
  # in bootstrap.conf:buildreq this time.
  - $LUAROCKS make $ROCKSPEC LUA="$LUA"
  - luarocks/bin/zemacs --version
  - luarocks/bin/zz --version

  # Check specifications.
  - LUA_PATH=`pwd`'/lib/?.lua;'"${LUA_PATH-;}" make check V=1

  # Check autotools installation.
  - $LUAROCKS remove $PACKAGE
  - ./configure LUA="$LUA" --prefix=`pwd`/_inst
  - make clean all install || lib/zz/zz --version
  - _inst/bin/zemacs --help
  - _inst/bin/zz --help
