# Lua is not officially supported, but an erlang environment will do.
language: erlang

env:
  global:
    - PACKAGE=zile
    - ROCKSPEC=zile-git-1.rockspec
    - LUAROCKS_BASE=luarocks-2.1.1
    - LDOC_ROCKSPEC=http://raw.github.com/gvvaughan/LDoc/next/ldoc-next-1.rockspec
  matrix:
    - LUA=lua5.2             LUA_INCDIR=/usr/include/lua5.2     LUA_SUFFIX=5.2

# Tool setup.
install:
  - sudo apt-get install lua5.2
  - sudo apt-get install liblua5.2-dev
  - sudo apt-get install help2man

  # Install a recent luarocks release.
  - wget http://luarocks.org/releases/$LUAROCKS_BASE.tar.gz
  - tar zxvpf $LUAROCKS_BASE.tar.gz
  - ( cd $LUAROCKS_BASE;
      ./configure
        --prefix=/usr/local --lua-version=$LUA_SUFFIX --lua-suffix=$LUA_SUFFIX
        --with-lua-include=$LUA_INCDIR;
      make;
      sudo make install; )
  - eval `luarocks path`

  # Put back the links for libyaml, which went missing on recent Travis VMs
  - test -f /usr/lib/libyaml.so ||
    sudo find /usr/lib -name 'libyaml*' -exec ln -s {} /usr/lib \;

  # Bootstrap checks this is available, so we need an early installation.
  - sudo luarocks install $LDOC_ROCKSPEC

# Configure and build.
script:
  # Make LUAROCKS_CONFIG to point at local rocks tree.
  - ./bootstrap
  - ./configure LUA="$LUA"
  - sudo luarocks remove ldoc
  - export LUAROCKS_CONFIG=build-aux/luarocks-config.lua
  - make $LUAROCKS_CONFIG LUA="$LUA" LUA_INCDIR="$LUA_INCDIR" V=1

  # Reset paths for local rocks tree.
  - eval `luarocks path`
  - PATH=`pwd`/luarocks/bin:$PATH

  # Make rockspecs.
  - luarocks install lyaml
  - make rockspecs V=1

  # Check installation from rockspec.
  - luarocks install $LDOC_ROCKSPEC
  - luarocks make $ROCKSPEC LUA="$LUA"
  - luarocks/bin/zmacs --version
  - luarocks/bin/zz --version

  # Check autotools installation.
  - luarocks remove $PACKAGE
  - ./configure LUA="$LUA" --prefix=`pwd`/_inst
  - make clean all install || lib/zz/zz --version
  - _inst/bin/zmacs --help
  - _inst/bin/zz --help
