# Lua is not officially supported, but an erlang environment will do.
language: erlang

env:
  global:
    - PACKAGE=zile
    - ROCKSPEC=zile-git-1.rockspec
    - LUAROCKS_CONFIG=build-aux/luarocks-config.lua
    - LUAROCKS_BASE=luarocks-2.1.1
    - LUAROCKS="$LUA $HOME/bin/luarocks"
  matrix:
    - LUA=lua5.2             LUA_INCDIR=/usr/include/lua5.2     LUA_SUFFIX=5.2

# Tool setup.
install:
  # Put back the links for libyaml, which went missing on recent Travis VMs
  - test -f /usr/lib/libyaml.so ||
    sudo find /usr/lib -name 'libyaml*' -exec ln -s {} /usr/lib \;

  - sudo apt-get install help2man
  - sudo apt-get install lua5.2
  - sudo apt-get install liblua5.2-dev

  # Install a recent luarocks release locally.
  - wget http://luarocks.org/releases/$LUAROCKS_BASE.tar.gz
  - tar zxvpf $LUAROCKS_BASE.tar.gz
  - ( cd $LUAROCKS_BASE;
      ./configure
        --prefix=$HOME --lua-version=$LUA_SUFFIX --lua-suffix=$LUA_SUFFIX
        --with-lua-include=$LUA_INCDIR;
      make;
      sudo make install; )

# Configure and build.
script:
  # Initial bootstrap to build luarocks-config.lua, before we've
  # installed our rocks.
  - ./bootstrap --skip-rock-checks
  - ./configure LUA="$LUA"
  - make $LUAROCKS_CONFIG
    LUA="$LUA" LUA_INCDIR="$LUA_INCDIR" V=1
    || cat $LUAROCKS_CONFIG config.log

  # Set Lua and Shell paths up for local luarocks tree.
  # this package depends on will be installed.
  - eval `$LUAROCKS path`
  - export PATH=`pwd`/luarocks/bin:$PATH

  # Install extra rocks into $LUAROCKS_CONFIG rocks tree.
  - $LUAROCKS install lyaml; $LUAROCKS install ldoc

  # Temporarily install specl git master (when specl 12 is released,
  # regenerate this file!).
  - $LUAROCKS install
    https://raw.githubusercontent.com/gvvaughan/specl/release-v11/specl-git-1.rockspec

  # Make git rockspec for zile
  - make rockspecs LUAROCKS="$LUAROCKS" V=1
    || { $LUAROCKS path; cat $ROCKSPEC; }

  # The git rockspec will rerun bootstrap, and check any rock versions
  # in bootstrap.conf:buildreq this time.
  - $LUAROCKS make $ROCKSPEC LUA="$LUA"
  - luarocks/bin/zmacs --version
  - luarocks/bin/zz --version

  # Check specifications.
  - LUA_PATH=`pwd`'/lib/?.lua;'"${LUA_PATH-;}" make check V=1

  # Check autotools installation.
  - $LUAROCKS remove $PACKAGE
  - ./configure LUA="$LUA" --prefix=`pwd`/_inst
  - make clean all install || lib/zz/zz --version
  - _inst/bin/zmacs --help
  - _inst/bin/zz --help
